## [Video](https://youtu.be/exaWOE8jvy8)

In [ ]:
import torch

## Initialzation and Some Basic Operations

In [2]:
x = torch.empty(2, 3)  # 2 row, 3 column
x

tensor([[-1.2997e-08,  4.5909e-41, -5.7702e-33],
        [ 4.5908e-41, -1.2852e-08,  4.5909e-41]])

In [3]:
y = torch.empty(3, 2, 3)
y, y.size()

(tensor([[[-3.6361e-32,  4.5909e-41, -3.6357e-32],
          [ 4.5909e-41, -3.6360e-32,  4.5909e-41]],
 
         [[-3.6363e-32,  4.5909e-41, -3.6363e-32],
          [ 4.5909e-41, -3.6361e-32,  4.5909e-41]],
 
         [[-3.6357e-32,  4.5909e-41, -3.6359e-32],
          [ 4.5909e-41, -8.9836e-35,  4.5908e-41]]]),
 torch.Size([3, 2, 3]))

In [4]:
rand_tensor = torch.rand(2, 2)
rand_tensor

tensor([[0.8037, 0.7534],
        [0.3065, 0.0553]])

In [5]:
zeros_tensor = torch.zeros(2, 2)
zeros_tensor, zeros_tensor.size()

(tensor([[0., 0.],
         [0., 0.]]),
 torch.Size([2, 2]))

In [7]:
ones_tensor = torch.ones(2, 2)
print(ones_tensor.type())
print(ones_tensor.dtype)

torch.FloatTensor
torch.float32


## In pytorch, every function in the trailing underscore will do a "In place operation"

In [10]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
z = y.add(x)
print(f"y={y} z={z}")


y.add_(x)
print(f"y={y}")

y=tensor([3, 4]) z=tensor([4, 6])
y=tensor([4, 6])


## Slice Tensor

In [13]:
x = torch.rand(5,3)

In [14]:
x

tensor([[0.2895, 0.1819, 0.8711],
        [0.5957, 0.8514, 0.6572],
        [0.9596, 0.2097, 0.0240],
        [0.5774, 0.5984, 0.9188],
        [0.6580, 0.0229, 0.4196]])

In [17]:
x[:, 0] # to get only first column

tensor([0.2895, 0.5957, 0.9596, 0.5774, 0.6580])

In [19]:
x[1, :] # row 1 with all columns

tensor([0.5957, 0.8514, 0.6572])

In [21]:
x[3, 1] # row 3 col 1

tensor(0.5984)

In [23]:
x[3, 1].item() # to get the actual value

0.5983633995056152

## Reshaping a tensor

In [25]:
x = torch.rand(4,4)

In [26]:
x

tensor([[0.9411, 0.7839, 0.4814, 0.6418],
        [0.4166, 0.9755, 0.6665, 0.2499],
        [0.7651, 0.0833, 0.0888, 0.5214],
        [0.6716, 0.5437, 0.5968, 0.3198]])

In [28]:
y = x.view(16)

In [29]:
y

tensor([0.9411, 0.7839, 0.4814, 0.6418, 0.4166, 0.9755, 0.6665, 0.2499, 0.7651,
        0.0833, 0.0888, 0.5214, 0.6716, 0.5437, 0.5968, 0.3198])

In [37]:
y = x.view(-1, 8)
y

tensor([[0.9411, 0.7839, 0.4814, 0.6418, 0.4166, 0.9755, 0.6665, 0.2499],
        [0.7651, 0.0833, 0.0888, 0.5214, 0.6716, 0.5437, 0.5968, 0.3198]])

In [38]:
y.size()

torch.Size([2, 8])

## Convertion between Numpy and Tensor 

In [42]:
import numpy as np

### Torch Tensor to Numpy

In [41]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [43]:
b = a.numpy()
b, type(b)

(array([1., 1., 1., 1., 1.], dtype=float32), numpy.ndarray)

#### a and b are pointed to the same object

In [46]:
a.add_(1)
a

tensor([2., 2., 2., 2., 2.])

In [47]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

### Numpy to Torch Tensor

In [55]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [56]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [57]:
a += 1
a

array([2., 2., 2., 2., 2.])

In [58]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

## With CUDA

In [61]:
if torch.cuda.is_available():
    device = torch.device('cuda')

In [62]:
x = torch.ones(5, device=device)

In [64]:
y = torch.ones(5)

In [66]:
x

tensor([1., 1., 1., 1., 1.], device='cuda:0')

In [67]:
y

tensor([1., 1., 1., 1., 1.])

In [70]:
y = y.to(device)

In [71]:
y

tensor([1., 1., 1., 1., 1.], device='cuda:0')

In [72]:
z = x+y

#### Numpy can only handle CPU tensor

In [73]:
z.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

### put tensor back to CPU

In [79]:
z = z.to('cpu')

In [80]:
z

tensor([2., 2., 2., 2., 2.])