# 00. PyTorch Fundamentals

### Ref: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import numpy as np
import torch

print(torch.__version__)

2.0.0


## Introdution to tensors

### Scalar

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.shape

torch.Size([])

In [5]:
scalar.item()

7

### Vector

In [6]:
vector = torch.tensor([6, 6])

In [7]:
vector

tensor([6, 6])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

### Matrix

In [13]:
matrix = torch.tensor([[7, 8], [9, 10]])

In [14]:
matrix.ndim

2

In [15]:
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [16]:
matrix[1]

tensor([ 9, 10])

In [17]:
matrix.shape

torch.Size([2, 2])

### TENSOR

In [53]:
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

In [54]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [55]:
TENSOR.shape

torch.Size([1, 3, 3])

In [56]:
TENSOR.ndim

3

In [57]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [58]:
TENSOR[0][2]

tensor([7, 8, 9])

In [59]:
TENSOR.T

tensor([[[1],
         [4],
         [7]],

        [[2],
         [5],
         [8]],

        [[3],
         [6],
         [9]]])

In [61]:
TENSOR.T.ndim

3

In [62]:
TENSOR.T.shape

torch.Size([3, 3, 1])

### Random Tensors

In [29]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4839, 0.7554, 0.1226, 0.2867],
        [0.7655, 0.8997, 0.0535, 0.9338],
        [0.4710, 0.6943, 0.5550, 0.9286]])

In [30]:
random_tensor = torch.rand((3, 4))
random_tensor

tensor([[0.4803, 0.9757, 0.6325, 0.8153],
        [0.1489, 0.0523, 0.8228, 0.1546],
        [0.0121, 0.5372, 0.2679, 0.0175]])

In [33]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))  # h, w, c
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [74]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [75]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [76]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [84]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
one_to_thous = torch.arange(start=0, end=1000, step=66)
one_to_thous

tensor([  0,  66, 132, 198, 264, 330, 396, 462, 528, 594, 660, 726, 792, 858,
        924, 990])

In [88]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [94]:
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False
)
float_32_tensor

tensor([3., 6., 9.])

In [95]:
float_32_tensor.dtype

torch.float32

In [96]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [100]:
print(float_16_tensor.dtype, float_32_tensor.dtype)
(float_16_tensor * float_32_tensor)

torch.float16 torch.float32


tensor([ 9., 36., 81.])

In [101]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [102]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [103]:
long_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
long_tensor

tensor([3, 6, 9])

In [104]:
long_tensor.dtype

torch.int64

## Getting info from tensors

In [106]:
some_tensor = torch.rand((3, 4))
some_tensor

tensor([[0.4151, 0.7141, 0.2802, 0.1205],
        [0.8654, 0.1277, 0.3842, 0.0980],
        [0.7725, 0.8815, 0.5056, 0.7136]])

In [108]:
some_tensor.dtype, some_tensor.shape, some_tensor.device

(torch.float32, torch.Size([3, 4]), device(type='cpu'))

In [110]:
some_tensor.size()

torch.Size([3, 4])

## Manipulating Tensors

In [119]:
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [120]:
tensor + 10

tensor([11, 12, 13])

In [121]:
tensor * 10

tensor([10, 20, 30])

In [122]:
tensor - 10

tensor([-9, -8, -7])

In [124]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [125]:
tensor * tensor

tensor([1, 4, 9])

In [126]:
tensor @ tensor

tensor(14)

## Finding the max, mean, sum, etc (tensor aggreagation)

In [128]:
x = torch.arange(0, 100, 10)

In [133]:
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [131]:
x.max()

tensor(90)

In [135]:
torch.mean(x, dtype=torch.float32)

tensor(45.)

In [136]:
x.type(torch.float32)

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [137]:
x.type(torch.float32).mean()

tensor(45.)

In [138]:
x.argmax()

tensor(9)

## reshaping, stacking, squeezing and unsqueezing tensors

In [152]:
x = torch.arange(1.0, 10.0)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [153]:
x_reshaped = x.reshape(1, 9)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [154]:
z = x.view((1, 9))
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [155]:
z[:, 0] = 5
z

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [156]:
x

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [160]:
x_stacked = torch.stack([x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.],
        [7., 7., 7.],
        [8., 8., 8.],
        [9., 9., 9.]])

In [161]:
v_stack = torch.vstack([x, x])
v_stack

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [162]:
h_stack = torch.hstack([x, x])
h_stack

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [163]:
torch.squeeze(x)

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [177]:
x = torch.zeros(2, 1, 2, 1, 2)
x.shape

torch.Size([2, 1, 2, 1, 2])

In [178]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [179]:
y = torch.squeeze(x, 0)
y.size()

torch.Size([2, 1, 2, 1, 2])

In [180]:
y = torch.squeeze(x, 1)
y.size()

torch.Size([2, 2, 1, 2])

In [181]:
y = torch.squeeze(x, (1, 2, 3))
y.shape

torch.Size([2, 2, 2])

In [182]:
x = torch.arange(1.0, 10.0)
x_reshaped = x.reshape(1, 9)
z = x.view((1, 9))
z, z.shape
z[:, 0] = 5
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [183]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [184]:
x_reshaped.squeeze().shape

torch.Size([9])

In [185]:
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [187]:
torch.unsqueeze(x_reshaped, 0)

tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]]])

In [189]:
x_original = torch.rand(size=(480, 640, 3))  # h, w, c

x_permuted = x_original.permute((2, 0, 1))  # c, h, w, 0 -> 1, 1 -> 2, 2 -> 0
x_permuted.shape

torch.Size([3, 480, 640])

In [195]:
x_original.shape

torch.Size([480, 640, 3])

In [199]:
x_original[0, 0, 0] = 6969

In [200]:
x_permuted

tensor([[[6.9690e+03, 2.1946e-01, 8.9201e-01,  ..., 3.7865e-01,
          6.7355e-01, 3.5178e-01],
         [9.4812e-01, 2.0153e-02, 4.5919e-01,  ..., 6.7838e-01,
          9.2865e-01, 6.6800e-01],
         [6.1158e-02, 3.8943e-01, 4.4394e-01,  ..., 3.7837e-01,
          3.8492e-01, 9.1547e-01],
         ...,
         [1.0959e-01, 2.4087e-01, 6.5077e-01,  ..., 7.8263e-02,
          4.4144e-01, 3.0225e-01],
         [4.9666e-01, 3.6504e-01, 5.1104e-01,  ..., 4.9693e-01,
          2.9587e-01, 8.1824e-01],
         [1.0358e-01, 2.5988e-01, 5.5960e-01,  ..., 3.5706e-02,
          8.0734e-02, 6.6570e-02]],

        [[6.1748e-01, 8.2170e-01, 4.8710e-01,  ..., 8.4765e-01,
          1.1972e-01, 1.1394e-01],
         [4.9810e-01, 9.3708e-02, 7.9401e-01,  ..., 8.5743e-01,
          9.7999e-02, 2.7294e-01],
         [1.0406e-01, 5.5755e-01, 5.9822e-01,  ..., 1.7993e-01,
          1.6726e-01, 5.4135e-01],
         ...,
         [7.0294e-01, 9.0582e-01, 4.8360e-01,  ..., 5.5233e-02,
          8.670

## Indexing

In [202]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [205]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [206]:
x[0][0][0]

tensor(1)

In [207]:
x[0][-1][-1]

tensor(9)

In [208]:
x[0][2][2]

tensor(9)

In [209]:
x[:, 0]

tensor([[1, 2, 3]])

In [211]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [213]:
x[:, 2, 2]

tensor([9])

## PyTorch tensors & Numpy

In [256]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [257]:
array[0] = 666

In [258]:
array

array([666.,   2.,   3.,   4.,   5.,   6.,   7.])

In [259]:
tensor

tensor([666.,   2.,   3.,   4.,   5.,   6.,   7.], dtype=torch.float64)

In [251]:
# torch.from_numpy(array).type(torch.float32)

In [254]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [255]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array += 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [263]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [265]:
tensor[0] = 666
tensor

tensor([666.,   1.,   1.,   1.,   1.,   1.,   1.])

In [266]:
numpy_tensor

array([666.,   1.,   1.,   1.,   1.,   1.,   1.], dtype=float32)

## Reproducbility

In [3]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8731, 0.7829, 0.5095, 0.4077],
        [0.7463, 0.1298, 0.7060, 0.3294],
        [0.4494, 0.3962, 0.3478, 0.2775]])
tensor([[0.1057, 0.5258, 0.3729, 0.0815],
        [0.1657, 0.9590, 0.6097, 0.1418],
        [0.5752, 0.9672, 0.5478, 0.0938]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [7]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3 ,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Check for GPU access with PyTorch

In [9]:
torch.cuda.is_available()

True

In [10]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [11]:
torch.cuda.device_count()

1

## Put tensors on the GPU

In [13]:
tensor = torch.tensor([1,2,3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [14]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Move tensors back to the CPU

In [16]:
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [18]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

### .item()

In [89]:
x = torch.tensor([[1]])
x.item(), x.ndim

(1, 2)

In [41]:
x = torch.tensor([1])
x.item(), x.ndim

(1, 1)

In [42]:
x = torch.tensor([[[1]]])
x.item(), x.ndim

(1, 3)

In [43]:
x = torch.tensor([[[1, 2, 3]]])
x.item(), x.ndim

RuntimeError: a Tensor with 3 elements cannot be converted to Scalar

In [47]:
x = torch.tensor([[1.0, -1.0], [1.0, 1.0]], requires_grad=True)
x

tensor([[ 1., -1.],
        [ 1.,  1.]], requires_grad=True)

In [48]:
out = x.pow(2).sum()
out

tensor(4., grad_fn=<SumBackward0>)

In [49]:
out.backward()

In [50]:
out

tensor(4., grad_fn=<SumBackward0>)

In [52]:
x.grad

tensor([[ 2., -2.],
        [ 2.,  2.]])

## CUDA

In [68]:
cuda = torch.device("cuda")
cuda0 = torch.device("cuda:0")

In [69]:
x = torch.tensor([1.0, 2.0], device=cuda0)

In [70]:
y = torch.tensor([1.0, 2.0]).cuda()

In [71]:
with torch.cuda.device(0):
    # allocates a tensor on GPU 1
    a = torch.tensor([1.0, 2.0], device=cuda)

    # transfers a tensor from CPU to GPU 1
    b = torch.tensor([1.0, 2.0]).cuda()
    # a.device and b.device are device(type='cuda', index=1)

    # You can also use ``Tensor.to`` to transfer a tensor:
    b2 = torch.tensor([1.0, 2.0]).to(device=cuda)
    # b.device and b2.device are device(type='cuda', index=1)

    c = a + b
    # c.device is device(type='cuda', index=1)

    z = x + y
    # z.device is device(type='cuda', index=0)

    # even within a context, you can specify the device
    # (or give a GPU index to the .cuda call)
    d = torch.randn(2, device=cuda0)
    e = torch.randn(2).to(cuda0)
    f = torch.randn(2).cuda(cuda0)
    # d.device, e.device, and f.device are all device(type='cuda', index=2)

    print(d, e, f)

tensor([-1.2798,  0.5277], device='cuda:0') tensor([ 2.0334, -0.5900], device='cuda:0') tensor([0.7156, 1.9148], device='cuda:0')


In [72]:
c

tensor([2., 4.], device='cuda:0')