In [1]:
import torch

In [3]:
x = torch.randn(3, requires_grad=True)
x

tensor([ 0.1721, -0.0496,  0.4676], requires_grad=True)

In [4]:
y = x + 2
y

tensor([2.1721, 1.9504, 2.4676], grad_fn=<AddBackward0>)

In [5]:
z = y * y * 2
z

tensor([ 9.4363,  7.6080, 12.1780], grad_fn=<MulBackward0>)

In [6]:
z = z.mean()
z

tensor(9.7407, grad_fn=<MeanBackward0>)

In [8]:
z.backward() # dz / dx

In [10]:
x.grad

tensor([2.8962, 2.6005, 3.2901])